# Generated by Django 4.1.7 on 2023-03-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=250)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.estados')),
            ],
        ),
    ]
