# Generated by Django 4.1.7 on 2023-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amigos',
            constraint=models.CheckConstraint(check=models.Q(('usuario_solicitante', models.F('usuario_receptor')), _negated=True), name='could_not_block_itself'),
        ),
    ]
