# Generated by Django 4.1.7 on 2023-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='ciudad',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to='main/imagenes/usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='pais',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
