# Generated by Django 4.1.7 on 2023-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuarios_ciudad_alter_usuarios_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='main/imagenes/usuarios'),
        ),
    ]
