# Generated by Django 4.1.7 on 2023-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_amigos_could_not_block_itself'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amigos',
            name='could_not_block_itself',
        ),
        migrations.AddConstraint(
            model_name='amigos',
            constraint=models.CheckConstraint(check=models.Q(('usuario_solicitante', models.F('usuario_receptor')), _negated=True), name='evitar_ser_amigo_de_uno_mismo'),
        ),
        migrations.AddConstraint(
            model_name='amigos',
            constraint=models.CheckConstraint(check=models.Q(('usuario_receptor', models.F('usuario_solicitante')), _negated=True), name='evitar_duplicidad_de_amigos'),
        ),
    ]
